# This file was generated from the BitbucketDataCenter CloudFormation template
INSTANCE_NAME=Bitbucket-Data-Center-BitbucketDCStack-1QKF2726B0LLN
BITBUCKET_URL=http://Bitbucket-LoadBala-7NUQHHR17OLF-161944117.ap-southeast-2.elb.amazonaws.com
BITBUCKET_HOME=/media/atl/bitbucket
BITBUCKET_UID=atlbitbucket
BITBUCKET_GID=atlbitbucket
BACKUP_HOME_TYPE=${BACKUP_HOME_TYPE:-amazon-ebs}
BACKUP_DATABASE_TYPE=${BACKUP_DATABASE_TYPE:-amazon-rds}
BACKUP_ARCHIVE_TYPE=
BACKUP_ELASTICSEARCH_TYPE=amazon-es
BACKUP_ZERO_DOWNTIME=true
HOME_DIRECTORY_MOUNT_POINT=/media/atl
HOME_DIRECTORY_DEVICE_NAME=/dev/sdf
RESTORE_HOME_DIRECTORY_VOLUME_TYPE=io1
RESTORE_HOME_DIRECTORY_IOPS=1000
FILESYSTEM_TYPE=zfs
ZFS_HOME_TANK_NAME=$(run sudo zfs list -H -o name,mountpoint | grep "${HOME_DIRECTORY_MOUNT_POINT}" | cut -f1)
RDS_INSTANCE_ID=bd1afsaxxf0ohsk
RESTORE_RDS_INSTANCE_CLASS=db.m4.large
RESTORE_RDS_MULTI_AZ=true
RESTORE_RDS_SUBNET_GROUP_NAME=bitbucket-data-center-bitbucketdcstack-1qkf2726b0lln-dbsubnetgroup-10amx6nw8mnyr
RESTORE_RDS_SECURITY_GROUP=sg-09cd192e1cac930b2
CURL_OPTIONS="-L -s -f"
AWS_REGION=ap-southeast-2
AWS_INFO=$(curl ${CURL_OPTIONS} http://169.254.169.254/latest/dynamic/instance-identity/document)
AWS_ACCOUNT_ID=$(echo "${AWS_INFO}" | jq -r .accountId)
AWS_AVAILABILITY_ZONE=$(echo "${AWS_INFO}" | jq -r .availabilityZone)
AWS_REGION=$(echo "${AWS_INFO}" | jq -r .region)
AWS_EC2_INSTANCE_ID=$(echo "${AWS_INFO}" | jq -r .instanceId)
AWS_ADDITIONAL_TAGS=
BITBUCKET_VERBOSE_BACKUP=${BITBUCKET_VERBOSE_BACKUP:-true}
KEEP_BACKUPS=5
ELASTICSEARCH_REPOSITORY_NAME=bitbucket-snapshots
ELASTICSEARCH_INDEX_NAME=bitbucket-search-v1
ELASTICSEARCH_S3_BUCKET=bitbucket-search-snapshots
ELASTICSEARCH_S3_BUCKET_REGION=ap-southeast-2
ELASTICSEARCH_SNAPSHOT_IAM_ROLE=arn:aws:iam::077491440934:role/Bitbucket-Data-Center-Bitb-BitbucketFileServerRole-F102UKEKHZC7
ELASTICSEARCH_HOST=search-bitbuck-elasti-z4erv5tqhy2s-ygog3u6pxmq42p34t6x4uhpybu.ap-southeast-2.es.amazonaws.com
